### ISSUE TITLE
API is down, database upgrade is stuck

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#14]

**Comment by rurseekatze** [comment]
The API works again.

The error was `An error occurred during facility request: "error: could not load library "/usr/pgsql-9.6/lib/postgis-2.4.so": /usr/pgsql-9.6/lib/postgis-2.4.so: undefined symbol: GEOSFrechetDistanceDensify" Aborting.`

I solved the problem with `yum remove geos36` (https://gis.stackexchange.com/questions/304621/qgis-3-online-postgresql-database-error-undefined-symbol-geosfrechetdistance).

**Comment by rurseekatze** [comment]
The update itself seems to work. For example, I changed the operator of this station a couple of days ago and the object was updated in the database:

- https://www.openstreetmap.org/node/27528737/history
- https://api.openrailwaymap.org/facility?uicref=8500087

I think the problem is the tile caching/expiry mechanism.

**Comment by DerDakon** [comment]
The database update timestamp is 4 days old.

**Comment by rurseekatze** [comment]
The update process works again. It failed because of the same PostGIS problem as the API. After I fixed the PostGIS problem, the next run of the cronjob was successful and applied all pending diffs.
