### ISSUE TITLE
Delivery to mailing list broken

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#39]
For a mail I sent on 2023-10-09 I just got a bounce with the following error:

```
<openrailwaymap@openrailwaymap.org>: connect to 127.0.0.1[127.0.0.1]:8024:
    Connection refused
```

**Comment by Nakaner** [comment]
`mailman3.service` was not running since 18 August 2023. On that day, I rebooted the after a hardware error (and replacement).

I don't know why it did not came up and cannot find anything about that in the logs (despite the logs still exist). The Systemd unit is enabled.

I started the unit a few minutes ago. Please try whether this solves the issue.

**Comment by DerDakon** [comment]
Works again (for now at least). I'll see if I can add it to my nagios.
